# vim:ft=kitty

## name: Aura Dark
## author: Adapted from OpenCode Aura theme
## blurb: A beautiful dark purple theme based on the Aura color palette.

#: The basic colors

foreground                      #edecee
background                      #0f0f0f
selection_foreground            #edecee
selection_background            #3d375e


#: Cursor colors

cursor                          #a277ff
cursor_text_color               #0f0f0f


#: URL underline color when hovering with mouse

url_color                       #82e2ff


#: kitty window border colors and terminal bell colors

active_border_color             #a277ff
inactive_border_color           #6d6d6d
bell_border_color               #ff6767
visual_bell_color               none


#: Tab bar colors

active_tab_foreground           #edecee
active_tab_background           #a277ff
inactive_tab_foreground         #6d6d6d
inactive_tab_background         #15141b
tab_bar_background              #0f0f0f


#: Colors for marks (marked text in the terminal)

mark1_foreground #0f0f0f
mark1_background #61ffca
mark2_foreground #0f0f0f
mark2_background #ffca85
mark3_foreground #0f0f0f
mark3_background #a277ff


#: The basic 16 colors

#: black
color0 #0f0f0f
color8 #6d6d6d

#: red
color1 #ff6767
color9 #ff6767

#: green
color2  #9dff65
color10 #9dff65

#: yellow
color3  #ffca85
color11 #ffca85

#: blue
color4  #82e2ff
color12 #82e2ff

#: magenta
color5  #a277ff
color13 #f694ff

#: cyan
color6  #61ffca
color14 #61ffca

#: white
color7  #edecee
color15 #ffffff
